// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPoJx7G12D3oQpmQlCR4o4h-wLzNsX030',
    appId: '1:1061200140405:web:6b32240f870624a8fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    authDomain: 'flutterprojefcts.firebaseapp.com',
    storageBucket: 'flutterprojefcts.appspot.com',
    measurementId: 'G-DF6MQBSZRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUMHgzJVcDSGOpygrV19hp-MmU_xfbklQ',
    appId: '1:1061200140405:android:1e451f9ae91caa43fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    storageBucket: 'flutterprojefcts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbHMsMrYCUHDq-NozklWQJib3OMs0I2Z8',
    appId: '1:1061200140405:ios:1e85e0d140069a71fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    storageBucket: 'flutterprojefcts.appspot.com',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbHMsMrYCUHDq-NozklWQJib3OMs0I2Z8',
    appId: '1:1061200140405:ios:55ba466f6586a8a9fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    storageBucket: 'flutterprojefcts.appspot.com',
    iosBundleId: 'com.example.marketplace.RunnerTests',
  );
}
